/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.menup;

import Clases.Orden;
import Clases.Restaurante;
import Clases.RestauranteGlobal;
import Default.sobreBoules;
import Default.vistaMenu;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;


/**
 *
 * @author angel
 */
public class ventanaPrincipal extends javax.swing.JFrame {
   RestauranteGlobal rest = new RestauranteGlobal();
    Restaurante r;
//Restaurante rest;
    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        this.r =rest.getR();
        initComponents();
                
//    r.getOrdene();
//    ArrayList<Orden> listaOrdenes = new ArrayList<Orden>();
    
//    r.setListaOrdenes(listaOrdenes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boules = new javax.swing.JLabel();
        modernKitchen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        modernKitchen1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        boules1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        modernKitchen2 = new javax.swing.JLabel();
        msjBtn = new javax.swing.JButton();
        menuvistaBtn = new javax.swing.JButton();
        reservarBtn = new javax.swing.JButton();
        pedirBtn = new javax.swing.JButton();
        verBtn = new javax.swing.JButton();

        boules.setFont(new java.awt.Font("Academy Engraved LET", 0, 30)); // NOI18N
        boules.setForeground(new java.awt.Color(255, 255, 255));
        boules.setText("B O U L E S");

        modernKitchen.setFont(new java.awt.Font("Academy Engraved LET", 0, 10)); // NOI18N
        modernKitchen.setForeground(new java.awt.Color(255, 255, 255));
        modernKitchen.setText("m  o  d  e  r  n   k  i  t  c  h  e  n ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        modernKitchen1.setFont(new java.awt.Font("Academy Engraved LET", 0, 10)); // NOI18N
        modernKitchen1.setForeground(new java.awt.Color(255, 255, 255));
        modernKitchen1.setText("m  o  d  e  r  n   k  i  t  c  h  e  n ");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        boules1.setFont(new java.awt.Font("Academy Engraved LET", 0, 30)); // NOI18N
        boules1.setForeground(new java.awt.Color(255, 255, 255));
        boules1.setText("B O U L E S");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        modernKitchen2.setFont(new java.awt.Font("Academy Engraved LET", 0, 10)); // NOI18N
        modernKitchen2.setForeground(new java.awt.Color(255, 255, 255));
        modernKitchen2.setText("m  o  d  e  r  n   k  i  t  c  h  e  n ");

        msjBtn.setBackground(new java.awt.Color(0, 0, 51));
        msjBtn.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        msjBtn.setForeground(new java.awt.Color(255, 255, 255));
        msjBtn.setText("Sobre nosotros");
        msjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msjBtnActionPerformed(evt);
            }
        });

        menuvistaBtn.setBackground(new java.awt.Color(0, 0, 51));
        menuvistaBtn.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        menuvistaBtn.setForeground(new java.awt.Color(255, 255, 255));
        menuvistaBtn.setText("Menú");
        menuvistaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuvistaBtnActionPerformed(evt);
            }
        });

        reservarBtn.setBackground(new java.awt.Color(0, 0, 51));
        reservarBtn.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        reservarBtn.setForeground(new java.awt.Color(255, 255, 255));
        reservarBtn.setText("Reservar una mesa");
        reservarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarBtnActionPerformed(evt);
            }
        });

        pedirBtn.setBackground(new java.awt.Color(0, 0, 51));
        pedirBtn.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        pedirBtn.setForeground(new java.awt.Color(255, 255, 255));
        pedirBtn.setText("Hacer orden de platillos");
        pedirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirBtnActionPerformed(evt);
            }
        });

        verBtn.setBackground(new java.awt.Color(0, 0, 51));
        verBtn.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        verBtn.setForeground(new java.awt.Color(255, 255, 255));
        verBtn.setText("Ver ordenes");
        verBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boules1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(modernKitchen2))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(verBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(menuvistaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(msjBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(reservarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pedirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boules1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modernKitchen2)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(msjBtn)
                .addGap(18, 18, 18)
                .addComponent(menuvistaBtn)
                .addGap(18, 18, 18)
                .addComponent(reservarBtn)
                .addGap(18, 18, 18)
                .addComponent(pedirBtn)
                .addGap(18, 18, 18)
                .addComponent(verBtn)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(modernKitchen1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(modernKitchen1)))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msjBtnActionPerformed
       sobreBoules s = new sobreBoules();
       s.setVisible(true);
        /*  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Boules");
        setSize(400, 350);
        setLocationRelativeTo(null); //Centrar la ventana

        
        String mensaje = "Tenemos un consumo máximo de 2 horas y media en caso requerir su mesa. Por su comprensión, Gracias. Los favoritos de la casa son los risottos, carpaccio de res, ostiones, lomo de cerdo, ceviche y ribeye. Recomendamos ordenar al centro para compartir a manera que todos compartan y prueben un poquito de todo. Vegetarianos o carnívoros, simple o sofisticado, jóvenes o mayores, Boules tiene algo para ti. Boules restaurante se localiza en el centro de Ensenada frente al parque revolución en el patio de La Contra, tienda de vinos donde puedes encontrar vinos de la región.";

        
        JTextArea textArea = new JTextArea(mensaje);
        textArea.setWrapStyleWord(true);
        textArea.setLineWrap(true);
        textArea.setOpaque(false);
        textArea.setEditable(false);
        textArea.setFocusable(false);

        
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setPreferredSize(new java.awt.Dimension(400, 300));

        
        JOptionPane.showMessageDialog(this, scrollPane);
        */
    }//GEN-LAST:event_msjBtnActionPerformed

    private void menuvistaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuvistaBtnActionPerformed
       // MenuVistaa menu = new MenuVistaa();
       vistaMenu menu = new vistaMenu(); 
       menu.setVisible(true);
        
    }//GEN-LAST:event_menuvistaBtnActionPerformed

    private void pedirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirBtnActionPerformed
       Menu m = new Menu(r);
       m.setVisible(true);
       //setVisible(false);
    }//GEN-LAST:event_pedirBtnActionPerformed

    private void reservarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarBtnActionPerformed
        
    }//GEN-LAST:event_reservarBtnActionPerformed

    private void verBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBtnActionPerformed
      // JOptionPane.showMessageDialog(null, "Las ordenes son"+"\n"+rest.getListaOrdenes().size());
      VerOrdenes v = new VerOrdenes();
      v.setVisible(true);
      
             
    }//GEN-LAST:event_verBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) { /* Set the Nimbus look and feel */ //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //Restaurante rest1 = new Restaurante();
    
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boules;
    private javax.swing.JLabel boules1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton menuvistaBtn;
    private javax.swing.JLabel modernKitchen;
    private javax.swing.JLabel modernKitchen1;
    private javax.swing.JLabel modernKitchen2;
    private javax.swing.JButton msjBtn;
    private javax.swing.JButton pedirBtn;
    private javax.swing.JButton reservarBtn;
    private javax.swing.JButton verBtn;
    // End of variables declaration//GEN-END:variables
}
